### ISSUE TITLE
Website Taken Down

### ISSUE THREAD

**Issue by bedantadey17** [dislandapp/disland#1]
![Screenshot_2023-09-22-12-58-31-28_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/dislandapp/disland/assets/135055975/d42fc040-2f42-412f-8bfd-865504b0a390)

![Screenshot_2023-09-22-12-58-25-14_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/dislandapp/disland/assets/135055975/1a3fafcf-621f-4ab4-92e5-772cf90f963c)

**Comment by andriemc** [comment]
no. its just not yet complete so it says that bc i was  using some cname thingy and cnames are allowlist based and didnt change the dns
